#ddev-generated
RUN curl https://goteleport.com/static/install.sh | bash -s 15.4.0 oss

RUN tsh config > ~/.ssh/teleport_config

RUN sed -i 's/%h/%n/g' ~/.ssh/teleport_config

RUN sed -i '1s/^/Include ~/.ssh/teleport_config/' ~/.ssh/config